# Generated by Django 4.2.7 on 2023-12-10 06:38

from django.db import migrations


def populate_countries(apps, schema_editor):
    Country = apps.get_model('mainapp', 'Country')

    Country.objects.bulk_create([
        Country(name='Russia'),
        Country(name='Slavyano-Ariyskaya Civilization'),
        # Add more countries as needed
    ])


def populate_genders(apps, schema_editor):
    Gender = apps.get_model('mainapp', 'Gender')

    # Populate genders
    Gender.objects.bulk_create([
        Gender(name='Male'),
        Gender(name='Female'),
        Gender(name='Non-Binary'),
        Gender(name='Binary'),
        Gender(name='Non-Hexadecimal'),
        Gender(name='Hexadecimal'),
        # Add more genders as needed
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_countries),
        migrations.RunPython(populate_genders),
    ]
