# Generated by Django 4.2.7 on 2023-12-10 09:30

from django.db import migrations
from django.core.files import File
import os


def load_country_flags(apps, schema_editor):
    flags_directory = 'images/country_flags'
    Country = apps.get_model('mainapp', 'Country')

    for filename in os.listdir(flags_directory):
        if filename.endswith('.png'):
            country_name = ' '.join([name_part.capitalize() for name_part in filename.replace('flag_', '').replace('.png', '').split('_')])
            country_flag_path = os.path.join(flags_directory, filename)

            country, created = Country.objects.get_or_create(
                name=country_name,
                defaults={'flag': f'images/country_flags/{filename}'})

            if created:
                print(f'Country {country_name} added')
            else:
                print(f'Country {country_name} updated')


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_populate_contries_and_genders'),
    ]

    operations = [
        migrations.RunPython(load_country_flags)
    ]
